clc;
am = input('Enter the amplitude:');
fm = input('Enter frequency:');
t = 0:0.02:2;
x = 1;
subplot(3,1,1);
stem(x);
xlabel('Time');
ylabel('Amplitude');
title('Impulse Signal');
x2 = am*sin(2*pi*fm*t);
subplot(3,1,2);
title('Sinusoidal Signal');
plot(t,x2);
ylim([-am-0.2 am+0.2]);
xlabel('Time');
ylabel('Amplitude');
y = x.*x2;
subplot(3,1,3);
title('PAM Waveform');
stem(t,y);
xlabel('Time');
ylabel('Amplitude');
ylim([-am-0.2 am+0.2]);